language: node_js
node_js:
  - "10"
before_install:
- openssl aes-256-cbc -K $encrypted_26b4962af0e7_key -iv $encrypted_26b4962af0e7_iv
  -in chrome-extension-key.pem.enc -out ~/chrome-extension-key.pem -d
before_script:
- wget https://github.com/yui/yuicompressor/releases/download/v2.4.8/yuicompressor-2.4.8.jar
- ln -s build_sys/mkcrxfolder.sh .
- ln -s build_sys/compress.sh .
- ./mkcrxfolder.sh -e0
before_deploy:
- export TRAVIS_TAG="2.9.$TRAVIS_BUILD_NUMBER"
- git tag -f $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: 'dist/tampermonkey.crx'
  skip_cleanup: true
  overwrite: true
  on:
    all_branches: true
after_deploy:
- ./xml.js
- export TRAVIS_TAG=update-${TRAVIS_BRANCH}
- git tag -f $TRAVIS_TAG
- dpl --provider=releases --api-key=$GITHUB_TOKEN --file=update.xml --overwrite=true --skip_cleanup
notifications:
  email: false
if: tag IS false
